### ISSUE TITLE
Split the slide into two parts

### ISSUE THREAD

**Issue by vinaykumar2491** [yhatt/marp-cli-example#10]
Hi @yhatt ,
As referenced here (https://marpit.marp.app/usage?id=extend-marpit-by-plugins) I should be able to split the slides. 
Is this possible to do it in `marp-cli` for web while hosting on NOW?

Thanks

**Comment by yhatt** [comment]
Add `engine` property to [`marp.config.js`](https://github.com/yhatt/marp-cli-example/blob/master/marp.config.js).

```javascript
// marp.config.js
const { Marp } = require('@marp-team/marp-core')
const container = require('markdown-it-container')

module.exports = {
  // Customize engine on configuration file directly
  engine: opts => new Marp(opts).use(container, 'custom'),
}
```

Please see the document at Marp CLI repository: https://github.com/marp-team/marp-cli#configuration-file
