### ISSUE TITLE
Template for website with multiple marp slides

### ISSUE THREAD

**Issue by harsh183** [yhatt/marp-cli-example#24]
I'm not sure where to post this but basically here my main issue is that `PITCHME.md` is nice but only one slide show. 

I am currently using marp to run a biweekly class and have a new slideshow for each day plus an index homepage. I've hosted it on Netlify [here](https://cs199emp.netlify.app/) and repo [here](https://github.com/harsh183/emp-125/). 

Right now I just make a new `.md` for each page, and then keep doing the `marp` command every time I change up something and manually add the link to the html part. I think it'll be nicer if there was some autobuild and update for many slides like how this manages it for `PITCHME.md`

**Comment by yhatt** [comment]
Sorry, I'm just showing the simplest and well-working one for Marp beginner. I'm taking a stance to leave some step-up examples, such as publishing multiple slides, to Marp community.

It would hardly get multi-deck build in this template because of losing the best SEO setting.

Wait someone to create the template, or try finding out the repository with similar usage that uses Marp CLI in wild.

**Comment by harsh183** [comment]
I ended up using the [Marp Github Action](https://github.com/marketplace/actions/marp-action) and a marp cli command call giving an input and output directory. Netlify points to the Github and auto updates based on that.

> because of losing the best SEO setting

If one were to make a template, how would it work with SEO settings?

**Comment by yhatt** [comment]
Check out [metadata section in Marp CLI documentation](https://github.com/marp-team/marp-cli#metadata).

[This repository is configured to set the canonical URL of slide deck from Netlify deploy environment automatically](https://github.com/yhatt/marp-cli-example/blob/master/marp.config.js#L5), and that requires single slide deck. (If changed this template to suit to multiple slide decks, a canonical URL of each decks may point to the wrong URL)
