### ISSUE TITLE
Unable to get background image to work

### ISSUE THREAD

**Issue by abhaybhargav** [yhatt/marp-cli-example#6]
I have a presentation in marp with the following directive
`![bg contain](img/logo.png)`
The img directory is also there in the git repo. However, the image doesn't load when loaded on netlify. 

Not sure what I am doing wrong here...

**Comment by yhatt** [comment]
Netlify executes `npm run build` to build deck, and the built HTML will be outputted to `dist/index.html`. Netlify only serves `dist` directory, so I guess that image assets in the out of `dist` directory are not served to Netlify.

If there is an `img` folder in the root of repository, you should update `deck` script in `package.json` to copy images from `./img` to `./dist/img` after building HTML. For example:

```javascript
// package.json: append "&& cp -r ./img ./dist/img"
{
  "scripts": {
    "deck": "marp --no-stdin PITCHME.md -o dist/index.html && cp -r ./img ./dist/img"
  }
}
```

**Comment by abhaybhargav** [comment]
Actually I solved that problem by pushing the images to amazon s3. But thanks for this suggestion. Ill keep in mind
