### ISSUE TITLE
Support request: host on Cloudflare Pages

### ISSUE THREAD

**Issue by pataquets** [yhatt/marp-cli-example#70]
Hello.
I've recently found Marp, which is awesome!
I see Netlify, Vercel and Gh pages examples and I wonder if marp could be as easily hosted on [Cloudflare Pages](https://pages.cloudflare.com/), too.
Due to my newbieness, I'm not sure if this should be a support or feature request.

**Comment by yhatt** [comment]
Yes. You already can host marp-cli-example to Cloudflare Pages.
https://developers.cloudflare.com/pages/get-started/

- Build command: `npm run deck`
- Build output directory: /`public`

**Comment by pataquets** [comment]
Works OK, thanks!
I've sent #74 to prevent further issues like this.
