### ISSUE TITLE
Unable to style my own css theme using this repo clone and hosting via NOW

### ISSUE THREAD

**Issue by vinaykumar2491** [yhatt/marp-cli-example#8]
Hi @yhatt,
Thanks a lot for this awesome software. I use it for everything locally & the CLI is great too. I am now trying to use it by hosting on NOW but it does not uses the custom CSS that I write....What should I do???

Thanks

**Comment by vinaykumar2491** [comment]
My slides overflow.....
![Screenshot-20190629182243-1859x1079](https://user-images.githubusercontent.com/12234745/60384415-f2c2bb00-9a9a-11e9-8228-89f863b541d7.png)

**Comment by yhatt** [comment]
Please show me your usage of the custom CSS.

**Comment by yhatt** [comment]
The structure of directories have updated to be able to use your theme in the static build correctly. (#9)

Could you try using theme in based on updated structure? (Put your theme to `themes` directory)

**Comment by vinaykumar2491** [comment]
Thanks @yhatt , I found that `<style> </style>` tag inside markdown works too. :smiley:
