### ISSUE TITLE
 How to host multiple Marp slides in one GitHub Pages repository?

### ISSUE THREAD

**Issue by mamintoosi** [yhatt/marp-cli-example#98]
Hi, I'm going to use Marp to create presentations for a course, and I want to host them on GitHub Pages. I have multiple topics in the course, and I want to have separate slides for each topic in the same repository. For example, I want to have something like this: [Lectures | archer2-cpp (epcced.github.io)](https://epcced.github.io/archer2-cpp/lectures/)
Is it possible with Marp? and if yes, How can I achieve this with Marp?

**Comment by yhatt** [comment]
Yes. You can modify [Marp CLI workflows](https://github.com/yhatt/marp-cli-example/blob/da954e14354bc4b37891cce6998c5ec50f7eb2c9/package.json#L7-L13) to input multiple Markdown files and output multiple HTMLs.

For example, this CLI command will input multiple markdown files in the `md` directory, and output HTML files to `html` directory.

```
marp --input-dir ./md -o ./html
```

```
$ tree
.
├── md
│   ├── 1.md
│   ├── 2.md
│   └── 3.md
└── html
    ├── 1.html
    ├── 2.html
    └── 3.html
```
